In [1]:
import torch
import copy
import numpy as np

from torch import nn

import sys
sys.path.append('/Users/khoanguyen-cp/gmu/network_properties')

from algorithms.iterative_relaxation import IterativeRelaxation
from algorithms.decision_procedure import MarabouCoreDP

from models.test_models import ProphecyPaperNetwork, TestModel
from models.utils import attach_relu_activation_hook, attach_layer_output_hook, get_layers_info
from models.utils import turn_bool_activation_to_str

Instructions for updating:
non-resource variables are not supported in the long term


### Test Improved DP

In [2]:
improved_dp = MarabouCoreDP()
prophecy_model = ProphecyPaperNetwork()

In [3]:
get_layers_info(TestModel())

[{'name': 'model_input', 'in_features': 2, 'out_features': 2, 'layer': None},
 {'name': 'sequential_stack.0',
  'in_features': 2,
  'out_features': 5,
  'layer': Linear(in_features=2, out_features=5, bias=False)},
 {'name': 'sequential_stack.1',
  'in_features': 5,
  'out_features': 5,
  'layer': ReLU()},
 {'name': 'sequential_stack.2',
  'in_features': 5,
  'out_features': 3,
  'layer': Linear(in_features=5, out_features=3, bias=False)},
 {'name': 'sequential_stack.3',
  'in_features': 3,
  'out_features': 3,
  'layer': ReLU()},
 {'name': 'final_output',
  'in_features': 3,
  'out_features': 2,
  'layer': Linear(in_features=3, out_features=2, bias=False)}]

In [5]:
activation = {
  'linear_relu_stack.1': ['ON', 'OFF'], 
  'linear_relu_stack.3': ['ON', 'OFF'],
}
input_ranges = [[-100, 100], [-100, 100]]
# specification = [(np.array([[1, -1]]), np.array([0]))] # class = y1
specification = [(np.array([[-1, 1]]), np.array([0]))] # class = y2
improved_dp.solve(activation, prophecy_model, input_ranges, specification)

Creating Input Query...
Parameter containing:
tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)
Parameter containing:
tensor([[ 0.5000, -0.2000],
        [-0.5000,  0.1000]], requires_grad=True)


['sat',
 {0: -49.999999,
  1: -50.000001,
  2: 1.9999999949504854e-06,
  3: -100.0,
  4: 1.9999999949504854e-06,
  5: 0.0,
  6: 0.0,
  7: 9.999999974752427e-07,
  8: -9.999999974752427e-07,
  9: 0.0,
  10: 9.999999974752427e-07,
  11: 0.0},

In [8]:
activation = {
  'linear_relu_stack.1': ['ON', 'OFF'], 
  'linear_relu_stack.3': ['--', '--'],
}
input_ranges = [[-100, 100], [-100, 100]]
# specification = [(np.array([[1, -1]]), np.array([0]))] # class = y1
specification = [(np.array([[-1, 1]]), np.array([0]))] # class = y2
improved_dp.solve(activation, prophecy_model, input_ranges, specification)

Creating Input Query...
Parameter containing:
tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)
Parameter containing:
tensor([[ 0.5000, -0.2000],
        [-0.5000,  0.1000]], requires_grad=True)


['sat',
 {0: -49.9999995,
  1: -50.0000005,
  2: 1e-06,
  3: -100.0,
  4: 1e-06,
  5: 0.0,
  6: 0.0,
  7: 5e-07,
  8: -5e-07,
  9: 0.0,
  10: 5e-07,
  11: 0.0},

In [10]:
activation = {
  'linear_relu_stack.1': ['--', '--'], 
  'linear_relu_stack.3': ['ON', '--'],
}
input_ranges = [[-100, 100], [-100, 100]]
specification = [(np.array([[1, -1]]), np.array([0]))]
specification = [(np.array([[-1, 1]]), np.array([0]))] # class = y2
improved_dp.solve(activation, prophecy_model, input_ranges, specification)

Creating Input Query...
Parameter containing:
tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)
Parameter containing:
tensor([[ 0.5000, -0.2000],
        [-0.5000,  0.1000]], requires_grad=True)


['sat',
 {0: -49.999999,
  1: -50.000001,
  2: 1.9999999949504854e-06,
  3: -100.0,
  4: 1.9999999949504854e-06,
  5: 0.0,
  6: 9.999999974752427e-07,
  7: -9.999999974752427e-07,
  8: 9.999999974752427e-07,
  9: 0.0,
  10: 9.999999974752427e-07,
  11: -9.999999974752427e-07},

### Test Iterative Relaxation

In [ ]:
ir_model = ProphecyPaperNetwork()
iterative_relaxation = IterativeRelaxation()

input_data = [[1, -1]]
input_ranges = [[-100, 100], [-100, 100]]
specification = [(np.array([[1, -1]]), np.array([0]))] # class = y1
# specification = [(np.array([[-1, 1]]), np.array([0]))] # class = y2

input_property = iterative_relaxation.call(ir_model, input_data, input_ranges, specification)
print(f"input property: {input_property}")

In [ ]:
ir_model = ProphecyPaperNetwork()
iterative_relaxation = IterativeRelaxation()

input_data = [[1, -1]]
input_ranges = [[-100, 100], [-100, 100]]
specification = [(np.array([[-1, 1]]), np.array([0]))] # class = y2

input_property = iterative_relaxation.call(ir_model, input_data, input_ranges, specification)
print(f"input property: {input_property}")

### Misc

In [ ]:
# model = ProphecyPaperNetwork()
# _act_handles, activation_signature = attach_relu_activation_hook(model)
# _out_handles, layer_outputs = attach_layer_output_hook(model)

# # input_data = [[-1,3]]
# input_data = [[1, -1]]
# # input_data = [[-10, -0]]

# X = torch.tensor(input_data, dtype=torch.float)
# logits = model(X)
# prediction_prob = nn.Softmax(dim=1)(logits)
# y_pred = prediction_prob.argmax(1)

# activation_signature = turn_bool_activation_to_str(activation_signature)

# print(f"Predicted class: {y_pred}")
# print(f"Activation: {activation_signature}")
# print(f"Layer outputs: {layer_outputs}")